### ISSUE TITLE
Criação do FEMUG-ABC

### ISSUE THREAD

**Issue by woliveiras** [braziljs/femug#70]
Fala galera!

Criei um grupo no Meetup para unir o pessoal aqui da região do ABC.
O 1º encontro aconteceu ontem, foi muito maneiro e o pessoal questionou sobre a criação de um FEMUG pelo formato ser interessante.
Esse é o Meetup: http://www.meetup.com/pt/front-abc/
Eu fiz um [fork do projeto na nossa organização](https://github.com/front-abc/femug), editei os arquivos necessários. Só falta enviar o pull request para avaliação.
Enviarei assim que me autorizarem. ;D

**Comment by augustoabreu** [comment]
+1!

**Comment by marciohiroyuki** [comment]
No aguardo =)

**Comment by augustoabreu** [comment]
+1!

**Comment by marquinhusgoncalves** [comment]
FEMUG-ABC a caminhoooo

**Comment by danvitoriano** [comment]
Com a plataforma do Femug dá pra discutir e votar o assunto das próximas talks, torcendo pra que role. :)

**Comment by danielfilho** [comment]
@woliveiras quem precisa autorizar que vc envie um pull-request?

**Comment by woliveiras** [comment]
É que na doc está escrito "Não faça um Pull Request sem antes abrir uma Issue". 
AUIEHUIHEUIAHEUIAEHAE
Achei que era um fluxo a ser seguido: Discutir sobre e depois fazer o pull. ;D
Valeu pelo retorno @danielfilho

**Comment by danielfilho** [comment]
AH, ok :D entendi.

o lance da issue é porque as vezes a galera quer criar mais de um femug num mesmo lugar. o que não faz muito sentido :)

**Comment by felipeuliana** [comment]
FEMUG-ABC a caminhoooo +1

**Comment by woliveiras** [comment]
KKKK
Entendi.
