### ISSUE TITLE
COC - Code of Conduct

### ISSUE THREAD

**Issue by raphamorim** [braziljs/femug#80]
Amigos responsáveis pelos FEMUGs.

Como está a relação ao Código de Conduta?

- Vocês são adeptos ao uso, se sim. Como vocês tem feito?
   - Linkando para COC?
       - Se sim, qual o link?
   - Disponiblizando em uma org no GitHub do próprio FEMUG?

Eu proponho a todos os FEMUGs o uso do COC e ainda a existência dele dentro do github para que possa ser forkado por outros e evoluido pelos integrantes. O que acham?

**Comment by rodneidesign** [comment]
-- Please reply above this line --


Oi! Como vai?

Eu não estou trabalhando agora, mas eu recebi sua mensagem e prometo
retornar logo pela manhã.

Obrigado!

**Comment by danielfilho** [comment]
@raphamorim hoje tem FEMUG-SP e eu vou anunciar a criação do COC do FEMUG, acredite ou não! Hahaha :)

Podemos usar esse PR pra discutir. Sou completamente a favor de um COC, já tive casos em encontros mas foi facilmente resolvido :)

Com certeza teremos um em breve. Vamos começar o papo sobre o assunto!

**Comment by raphamorim** [comment]
Adicionando interessados na thread: @leobalter, @fnando para poder ajudar a montar algo decente.

**Comment by raphamorim** [comment]
Ótimo @danielfilho :)

Acho que o COC deveria ser pessoal de cada FEMUG, however ele deveria ser um fork de uma base que a gente pode montar.

**Comment by danielfilho** [comment]
com certeza. vou discutir sobre isso hoje e, com certeza, implementar um como padrão dos encontros :)

**Comment by raphamorim** [comment]
Show. O resultado da conversa de hoje no FEMUG-SP, atualiza e dá as ideias nessa issue @danielfilho. Vou conversar também com a galera do RJ

**Comment by raphaelfabeni** [comment]
Pessoal, participei dessa edição do FEMUG-SP e a discussão foi bem bacana. O @danielfilho disse algo bacana, relacionando o código de conduta como um *polyfill*. 
Aproveito pra falar, vou acompanhar a discussão, pois quero levar o código para o *meetup CSS*.

**Comment by rodneidesign** [comment]
-- Please reply above this line --


Oi! Como vai?

Eu não estou trabalhando agora, mas eu recebi sua mensagem e prometo
retornar logo pela manhã.

Obrigado!

**Comment by raphamorim** [comment]
Boa @raphaelfabeni !
As mensagens do @rodneidesign são as melhores hahaha

**Comment by rodneidesign** [comment]
-- Please reply above this line --


Oi! Como vai?

Eu não estou trabalhando agora, mas eu recebi sua mensagem e prometo
retornar logo pela manhã.

Obrigado!

**Comment by taltk9** [comment]
Eu sou a favor do COC.
Não estamos usando nada em Santa Maria, mas deixamos bem claro como 
devemos nos portar em eventos deste formato.
Estarei a disposição no que precisar de ajuda...


Att,
Thiago Alves Luiz
FULL STACK WEB DEVELOPER
twitter	@taltk9
linkedin	thiagoalvesluiz
github	taltk9


Em Qua, Set 2, 2015 em 7:53 , Raphael Amorim <notifications@github.com> 
escreveu:

**Comment by rodneidesign** [comment]
-- Please reply above this line --


Oi! Como vai?

Eu não estou trabalhando agora, mas eu recebi sua mensagem e prometo
retornar logo pela manhã.

Obrigado!

**Comment by danielfilho** [comment]
Pessoal,

Adicionei o código de conduta, mas vou deixar a thread pra discutirmos ok? Achei super bem feito e adequado pro grupo.

No entanto, se for o caso, podemos fazer um fork (ao invés de manter como submodule) e personalizarmos.

**Comment by raphamorim** [comment]
Boa @danielfilho 

No FEMUGRJ optamos estamos usando o seguinte CdC: https://github.com/FEMUGRJ/code-of-conduct
Para quem quiser levantar sugestões ou reutilizar como base em outros FEMUGs :)
